### ISSUE TITLE
On Button Action 

### ISSUE THREAD

**Issue by imuhammadjabbar** [Ahmadalsofi/SOPullUpView#1]
What If I want to show the pullup view on a button action instead of handle area?

**Comment by Ahmadalsofi** [comment]
Hey Muhammad, 

Please update your current SPPullUpView pod version to the latest one, and you can call expaned and collapsed method to customaize your action call. 

Thank you

**Comment by imuhammadjabbar** [comment]
Sure @Ahmadalsofi I'll update and let you know as soon as possible. Thanks for replying quickly and fixing it. :)
