### ISSUE TITLE
Wrong frames when using view controllers from xib

### ISSUE THREAD

**Issue by Gargo** [Ahmadalsofi/SOPullUpView#2]
[Fumedeck.zip](https://github.com/Ahmadalsofi/SOPullUpView/files/3990141/Fumedeck.zip)
here is my project example. The code is similar to your own example but I don't like storyboards. The problem is view width is smaller than expected (while frame is calculated correctly)

**Comment by Ahmadalsofi** [comment]
Hey @Gargo , 

did you check the new version?

**Comment by shashi751** [comment]
I used the code as below 
   if sender.currentTitle == "Show"{
            pullUpControl.setupCard(from: view)
            sender.setTitle("Hide", for: .normal)
        }else{
            pullUpControl.hide()
            sender.setTitle("Show", for: .normal)
        }
first time it setUp the view and display the pullupview but when it hides in else condition it will never show up even if it goes to if condition. Please suggest the fix.
